### PR TITLE
Proposal

### PR DESCRIPTION
**Pull request by alexkwolfe**
Here are a few changes that occurred to me. Each commit pretty much encapsulates one thing I would have suggested on a regular pull request.

### CODE REVIEW

**Comment by alexkwolfe** [comment]
@zalary, have you looked at this? We need to have this deployed to production by Monday. I'm happy to help. Just let me know.

**Comment by zalary** [comment]
sorry, this completely fell off my radar :(  

I understand the changes you propose and actually does some of the work I was planning for the next iteration :) 

LGTM

**Comment by zalary** [comment]
would you like me to merge this in and update the version and npm publish?

**Comment by alexkwolfe** [comment]
Sure

**Pull request merged**
